apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
  labels:
    {{- include "orders.labels" . | nindent 4}}
    app.kubernetes.io/component: orders

spec:
  replicas: {{ .Values.orders.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: orders
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: orders
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: orders
          image: {{ .Values.orders.image }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 1
            httpGet:
              path: /
              port: 3000
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 1
            httpGet:
              path: /
              port: 3000