apiVersion: v1
kind: Secret
metadata:
  name: mongodb
  labels:
    app.kubernetes.io/component: mongodb
    {{- include "orders.labels" . | nindent 4}}
type: Opaque
data:
  orders_db_url: {{ .Values.ordersMongoUrl | b64enc }}